---
- name: install openvpn with self-service certificatation authority
  hosts: all
  become: true
  tasks:

  - name: Install openvpn
    ansible.builtin.apt:
      name: openvpn
      state: latest

  - name: Install python openssl pip package
    ansible.builtin.pip:
      name: pyopenssl

  - name: create the vpn-self-service-group
    ansible.builtin.group:
      name: vpn-self-service
      state: present

  - name: Add the user 'student'
    ansible.builtin.user:
      name: student
      state: present
  
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: student
      state: present
      key: "{{ lookup('file', 'id_ed25519.pub') }}"

  - name: Add the user 'vpn-self-service'
    ansible.builtin.user:
      name: vpn-self-service
      group: vpn-self-service
      home: /etc/openvpn/server/
      state: present

  - name: Write the openvpn config file
    ansible.builtin.template:
      src: server.conf.j2
      dest: /etc/openvpn/server/server.conf

  - name: set pki directory permissions
    ansible.builtin.file:
      path: /opt/pki
      owner: root 
      group: vpn-self-service
      state: directory
      mode: '0750'

  - name: openvpn CA cert
    ansible.builtin.copy:
      src: /opt/pki/ca.crt 
      dest: /etc/openvpn/server/ca.crt
      owner: root
      group: vpn-self-service
      mode: '0644'

  - name: CA key
    ansible.builtin.file:
      path: /opt/pki/ca.key
      owner: root
      group: vpn-self-service
      mode: '0660'

  - name: openvpn server cert
    ansible.builtin.copy:
      src: /opt/pki/server.crt
      dest: /etc/openvpn/server/server.crt
      owner: root
      group: root
      mode: '0600'

  - name: openvpn key
    ansible.builtin.copy:
      src: /opt/pki/server.key
      dest: /etc/openvpn/server/server.key
      owner: root
      group: root
      mode: '0600'

  - name: gen-dh
    ansible.builtin.command:
      cmd: "openssl dhparam -out /etc/openvpn/server/dh2048.pem 2048"
      chdir: /etc/openvpn/server
      creates: /etc/openvpn/server/dh2048.pem

  - name: Write the openvpn config file
    ansible.builtin.template:
      src: server.conf.j2
      dest: /etc/openvpn/server/server.conf

  - name: sudoers vpn-self-service 
    ansible.builtin.template:
      src: sudoers
      dest: /etc/sudoers.d/vpn-self-service

  - name: install 'ca.py'
    ansible.builtin.copy:
      src: ca.py 
      dest: /usr/local/bin/ca.py
      owner: root
      group: root
      mode: '0755'

  - name: Write the nat script file
    ansible.builtin.template:
      src: nat.sh 
      dest: /etc/openvpn/server/nat.sh

  - name: enable openvpn server in defaults
    lineinfile:
      dest: /etc/default/openvpn
      regexp: '^\AUTOSTART=\".+\"$'
      line: 'AUTOSTART="all"'

  - name: ensure that openvpn is started
    ansible.builtin.service:
      name: 'openvpn-server@server.service'
      state: restarted

  - name: Enable IP forwarding
    sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

